[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "voicecmd"
version = "0.2.0"
description = "Voice command recognizer (FFT + band energies) — OOP, sounddevice-based"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "scipy",
  "sounddevice",
  "soundfile",
  "typer",
  "fastapi",
  "uvicorn[standard]",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
voicecmd = "voicecmd.cli:app"
voicecmd-gui = "voicecmd.gui:main"